# This is a basic workflow to help you get started with Actions

name: TryHackMe Badge

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Update Badge
        run: echo Updated!

      # Runs a set of commands using the runners shell
      - name: TryHackMe Badge Action Workflow
        uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
        with:
         image_path: './assets/tryhackme-badge.png'
         username: ${{secret.USERNAME}}
         user_id: ${{secret.USERNAME}}
         GITHUB_TOKEN: ${{secret.PROFILE_TOKEN}}
